#TUGAS 3
#BUAT PERHITUNGAN RUMUS VOLUME PERSEGI PANJANG MENGGUNAKAN PYTHON, MASING-MASING NILAI VARIABEL DIINPUTKAN COMMAND KEMUDIAN KETIKA KODE DIEKSEKUSI MAKA AKAN MENAMPILKAN HASIL DARI PERHITUNGAN TADI
# RUMUS VOLUME = PANJANG X LEBAR X TINGGI
# BUAT VARIABEL SESUAI YANG DIBUTUHKAN DALAM VARIABEL TERSEBUT
p = input(memasukan ukuran panjang)
le = input (memasukan ukuran lebar)
lu = p*le
print(lu)
