#TUGAS 4
#MEMBUAT KONDISI DARI SEBUAH PERHITUNGAN LUAS PERSEGI
#JIKA HASIL LUAS DARI PERSEGI LEBIH DARI 100 MAKA AKAN MENAMPILKAN TULISAN 'GEDE BANGET BRO'
#JIKA HASIL LUAS DARI PERSEGI KURANG DARI 100 MAKA AKAN MENAMPILKAN TULISAN 'KECIL BANGET BRO'
#RUMUS LUAS PERSEGI = SISI^2